### ISSUE TITLE
::class references not detected

### ISSUE THREAD

**Issue by elazar** [Insolita/unused-scanner#1]
Under one of the directories included in the `scanDirectories` setting, if a PHP file returning an array contains a use of `::class`, usage of the referenced class will not be detected. In my case, the reference was `Opauth\OpenID\Strategy\OpenID::class` and the associated library was `opauth/openid`.

**Comment by Insolita** [comment]
can you public peace of code with this array?

**Comment by elazar** [comment]
The code is below. It uses a fully qualified class reference, which I suspect is why this tool didn't detect it.

```php
<?php defined('SYSPATH') or die('No direct script access.');

return [
    'Strategy' => [

        // OpenID Setup
        'QuickBooks' => [
            '_name' => Opauth\OpenID\Strategy\OpenID::class,
            'openid_url' => 'https://openid.intuit.com/openid/xrds',
            'required' => [
                'namePerson',
                'contact/email',
            ],
            'optional' => [
                'namePerson/first',
                'namePerson/last',
                'intuit/realmId',
            ]
        ],
    ],
    'path'        => '/auth/connect/',
    'callback'    => 'callback',
    'http_client' => 'Opauth\\Opauth\\HttpClient\\Guzzle3'
];
```

**Comment by elazar** [comment]
Related note: you may want to consider changing your approach to use something like [nikic/php-parser](https://github.com/nikic/PHP-Parser). While parsing `use` statements may be sufficient for many, perhaps even most, use cases, use of fully qualified class names can and often is done without `use` statements (e.g. for classes only referenced once within a single file).

**Comment by Insolita** [comment]
i check not only "use" statements, troubles was with double slashes; new version should fix it

**Comment by elazar** [comment]
Appears that did indeed fix it; the dependency no longer shows up as unused under 1.0.6. Thank you for the prompt reply. 😄
