### ISSUE TITLE
'php' reported as an unused dependency after adding 'hyn/multi-tenant' as dependency

### ISSUE THREAD

**Issue by kalessil** [Insolita/unused-scanner#10]
#### Php version: 
PHP 7.2.5-1+ubuntu16.04.1+deb.sury.org+1
#### Os: 
ubuntu16.04.1
#### Composer packages with detection troubles: 
hyn/multi-tenant
#### Which type of autoload it uses? 
PSR4

When adding the package, scanner starts complaining:
```
Unused dependencies found!
 -php
```

**Comment by kalessil** [comment]
Also, thank you for a great tool!

**Comment by Insolita** [comment]
ok, i `m going to fix it as soon as i have free time

**Comment by stelgenhof** [comment]
Thanks for the very useful tool! To add to this issue, you might want to ignore PHP extensions as well.
