### ISSUE TITLE
[Feature Request] Config file optional

### ISSUE THREAD

**Issue by stelgenhof** [Insolita/unused-scanner#12]
Would it be possible to make the parameter for the config file optional? Meaning that if the standard 'scanner_config.php' is present in the projects' root, allowing the tool to run without the config parameter. If the config filename is different, then of course it can still be used with the parameter.

Not a big request, but saves some typing :)

Cheers! Sacha

**Comment by stelgenhof** [comment]
Wow! You're fast

**Comment by Insolita** [comment]
You wrote it at a good time.
