### ISSUE TITLE
It's not working on windows

### ISSUE THREAD

**Issue by b1rdex** [Insolita/unused-scanner#13]
1. outputs only first dir from defined $scanDirectories
2. scans very very fast (no files I guess?)
3. always says `Unused dependencies not found!`

I tried to use DIRECTECTORY_SEPARATOR in config with no luck. Same config works good on linux.

**Comment by Insolita** [comment]
I fix some places with DIRECTORY_SEPARATOR, but i havent Windows for check it, and main goal is Linux OS
