### ISSUE TITLE
Unused-scanner scans only first directory from the list and founds nothing

### ISSUE THREAD

**Issue by TeslaX93** [Insolita/unused-scanner#17]
#### Composer packages with detection troubles: all

I tried to test unused-scanner on my Laravel project. Following the manual, I've installed scanner via composer, created scanner_config.php in root directory and...

It does not work. After preparing stage (less than a second), scanner takes first directory from $scanDirectories array, returns "No unused depedencies found" and quits.

> D:\htest\test>unused_scanner scanner_config.php
> - config prepared
> - search patterns prepared
>
> - Scan D:\htest\test\app\
>100%[============================================================>]
>No unused dependencies found!

My scanner_config.php:

`<?php                      
$projectPath = __DIR__ ;
//Declare directories which contains php code
$scanDirectories = [                           
   $projectPath . '/app/',                           
   $projectPath . '/config/',                           
   $projectPath . '/resources/views/',
   $projectPath. '/routes/'                                                               
];
//Optionally declare standalone files
$scanFiles = [                           
     $projectPath . '/AuthenticatesUsers.php',                       
];
return [
'composerJsonPath' => $projectPath . '/composer.json',                              
'vendorPath' => $projectPath . '/vendor/',
'scanDirectories' => $scanDirectories,
'scanFiles'=>$scanFiles
];`

**Comment by Insolita** [comment]
You use windows, try to cahnge '/' in paths to constant DIRECTORY_SEPARATOR

**Comment by TeslaX93** [comment]
@Insolita unfortunately, it's still the same

**Comment by pardeep26k** [comment]
Same issues to me.

**Comment by Insolita** [comment]
maybe #18 will fix it, i  will check it at weekend

**Comment by Insolita** [comment]
@TeslaX93 @pardeep26k 
Anybody can attach vendor/composer/autoload_psr4.php from your active project on windows?

**Comment by Insolita** [comment]
In 1.3 and 2.0 versions have been added path normalizer, it should solve windows problem. I wait for feedback
