### ISSUE TITLE
"??" is not compatible with php 5.6

### ISSUE THREAD

**Issue by michabbb** [Insolita/unused-scanner#20]
https://github.com/Insolita/unused-scanner/blob/e710c5a410fa5db0bf0a57602a591fbad6b28a3b/unused_scanner#L21

`Parse error: syntax error, unexpected '?'`

**Comment by Insolita** [comment]
use branch 1.3 https://github.com/Insolita/unused-scanner/tree/1.3

**Comment by peter279k** [comment]
This syntax is only for `php-7.x`.

**Comment by michabbb** [comment]
oh, what an old issue 😏 thanks for your feedback!
