### ISSUE TITLE
Missing licence

### ISSUE THREAD

**Issue by bdsl** [Insolita/unused-scanner#21]
It looks like there is no licence specified for this software, [so people who might wish to use it don't have explicit permission to do so](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license).

Please consider adding an open source / free software licence.

**Comment by bdsl** [comment]
Thank you

**Comment by Insolita** [comment]
The license noted in composer.json as MIT. I think about license text. Thanks for advice

**Comment by bdsl** [comment]
Thanks Insolita - I didn't think to look in the composer.json file. I think adding a note to the readme and a licence file to the root folder will make it a lot clearer.

**Comment by dmaroulidis** [comment]
Hi! I'd be more than happy to update the README and add a LICENCE file with the MIT licence.

**Comment by dmaroulidis** [comment]
I've made PR #22 adding the MIT licence to a LICENCE file and adding a notice in README.md

**Comment by Insolita** [comment]
Merged, Thanks!
