### ISSUE TITLE
Fix travis for pass tests with php 7.1 version

### ISSUE THREAD

**Issue by Insolita** [Insolita/unused-scanner#23]
https://travis-ci.org/Insolita/unused-scanner/jobs/597326932

**Comment by ahhmarr** [comment]
can I work on it ??

**Comment by disc** [comment]
As a fix #24, I suppose to downgrade phpunit version to ^7 instead of using both versions.
PHPUnit 7 supports PHP 7.1 - 7.3

Updated: Found simplest way #26
