### ISSUE TITLE
skipPackages Not working

### ISSUE THREAD

**Issue by juanmrad** [Insolita/unused-scanner#29]
#### Php version:

7.2

#### Os:
Docker on Mac

#### Composer packages with detection troubles:

`ramsey/uuid`

#### Code example of package classes usage that not detected:

The package is a suggested package by one library I use. since it is not require composer won't install it. I have installed it using composer require, but then I am not using it on my project directly. I tried adding it as such:

```php
    'skipPackages' => [
        'ramsey/uuid',
    ],
```

on my config, but it is still reporting it as unused. is this how it is supposed to work? or is there any other way to configure it.

**Comment by juanmrad** [comment]
Nevermind. I was using the docker option that was mentioned on the readme, but that docker image has not been updated for 2 years. 

I created a new docker image using the latest code changes and it worked as expected:
For anyone having this issue this is my docker image repo:

https://hub.docker.com/r/juanmrad/unused-scanner

**Comment by Insolita** [comment]
Hi, thanks for the response. I add a link to your repository in documentation
