### ISSUE TITLE
unused_scanner command not found

### ISSUE THREAD

**Issue by krutik2403** [Insolita/unused-scanner#31]
#### Os:Ubuntu 20.04 LTS

I followed the instructions mentioned in the read me file but it did not work and gave me the command not found.

**Comment by Insolita** [comment]
put in your ~/.bashrc  (if you use zsh  ~/.zshrc file)

`export PATH="$PATH:$HOME/.composer/vendor/bin"` or 
`export PATH="$PATH:$HOME/.config/composer/vendor/bin"`
  (or another valid path, if you use custom composer directory) You can find it with command `composer config --global home`

**Comment by madurapa** [comment]
`source ~/.bashrc` should be executed to update the new PATH
