### ISSUE TITLE
Feature request: Distribute as phar

### ISSUE THREAD

**Issue by martinssipenko** [Insolita/unused-scanner#33]
Do you have any plans to distribute this project as phar? Having to `composer install` it globally or on project scope might introduce dependency conflicts. Also, installing this project as a phar would simplify the install process.

Many other similar projects do recommend that they are installed as phar - [Composer Require Checker](https://github.com/maglnet/ComposerRequireChecker#installation--usage), [Symfony Security Checker](https://github.com/sensiolabs/security-checker#usage), [Infection](https://infection.github.io/guide/installation.html#Phar), etc.

I'd be happy to contribute if you think this would be something you are willing to accept.

**Comment by Insolita** [comment]
I don't think about it yet, but it sounds good. PR welcome
