### ISSUE TITLE
Feature request: Usage log

### ISSUE THREAD

**Issue by elazar** [Insolita/unused-scanner#7]
It would be nice if the scanner was able to log instances of usage that it found per dependency (i.e. the name of the dependency and paths to the source files that use it) so that dependencies with minimal usage could be removed or replaced.

**Comment by Insolita** [comment]
Yes, i think about usage log. Probably it can be stored as report file.

**Comment by Insolita** [comment]
Done

**Comment by elazar** [comment]
This is excellent! Thank you! 😃
